version: "3.8"

services:
  TesteRelatorio.Api:
    image: mffolhaconteinerregistry.azurecr.io/testerelatorio:latest
    build:
      context: ./
      dockerfile: ../Dockerfile
    ports:
      - 5004:5004
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://*:5004
    networks:
      - controle
  
networks:
  controle:
    driver: bridge