version: "3.8"

services:
  novafolha.relatorio.api:
    image: mffolhaconteinerregistry.azurecr.io/api:latest
    build:
      dockerfile: Api/Dockerfile
    ports:
      - 5004:5004
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://*:5004
    networks:
      - controle
  
networks:
  controle:
    driver: bridge